/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API keys that can sign in to this server. */
        get: operations["list_api_keys"];
        put?: never;
        /** Creates an API key. The key is returned only in this response. */
        post: operations["create_api_key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revokes an API key. */
        delete: operations["revoke_api_key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/definitions/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validates a definition without saving it. */
        post: operations["check_definition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/definitions/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Converts a Jackett (Cardigann) definition. Nothing is saved. */
        post: operations["convert_definition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/definitions/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs a definition once, live, without saving it. */
        post: operations["preview_definition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/definitions/starter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A commented starter definition. */
        get: operations["starter_definition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A saved definition's YAML. */
        get: operations["get_definition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Saved results, newest first. */
        get: operations["list_favorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Saves a result from a recent search. */
        put: operations["add_favorite"];
        post?: never;
        delete: operations["remove_favorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check. No authentication. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent searches, newest first. */
        get: operations["get_history"];
        put?: never;
        post?: never;
        /** Deletes all search history. */
        delete: operations["clear_history"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/network/tor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State of built-in Tor (connecting, ready, or not running). */
        get: operations["tor_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists every provider with its state and health. */
        get: operations["list_providers"];
        put?: never;
        /** Adds a provider. Re-adding a definition with the same id updates it. */
        post: operations["add_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One provider. */
        get: operations["get_provider"];
        put?: never;
        post?: never;
        /** Removes a user-added provider. */
        delete: operations["delete_provider"];
        options?: never;
        head?: never;
        /** Changes a provider (enable/disable, rename, network policy). */
        patch: operations["update_provider"];
        trace?: never;
    };
    "/providers/{id}/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stores cookies from a browser check the user completed on the site
         *     (desktop "Open site to continue").
         */
        post: operations["set_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs a provider's self-test now. */
        post: operations["test_provider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Definition repositories, including the built-in one. */
        get: operations["list_repos"];
        put?: never;
        /** Adds a signed definition repository. Its providers are added disabled. */
        post: operations["add_repo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Removes a repository and its providers. */
        delete: operations["remove_repo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repos/{id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetches a repository's latest definitions now. */
        post: operations["sync_repo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gets the magnet link or `.torrent` URL for a result. */
        post: operations["resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/results/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A result from a recent search. */
        get: operations["get_result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Streams a search as Server-Sent Events.
         * @description Event names: `provider_started`, `results`, `provider_finished`,
         *     `provider_failed`, `done`. Each event's data is the JSON of a
         *     `SearchEvent`. `results` items with an `id` seen before replace it.
         *     Closing the connection cancels the search.
         */
        get: operations["search_stream"];
        put?: never;
        /** Runs a search to completion and returns sorted results. */
        post: operations["search_blocking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current settings. */
        get: operations["get_settings"];
        /** Replaces all settings. Fields left out take their defaults. */
        put: operations["put_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/fetch-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetches a page for the definition editor's element picker. */
        post: operations["fetch_page"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trackers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trackers added to magnets. */
        get: operations["list_trackers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trackers/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Downloads the tracker list from the configured URL now. */
        post: operations["refresh_trackers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description How to add a provider. */
        AddProvider: {
            /** @enum {string} */
            kind: "definition";
            yaml: string;
        } | {
            api_key?: string | null;
            /** @enum {string} */
            kind: "torznab";
            name: string;
            url: string;
        };
        AddRepoRequest: {
            /** @description The repository folder or its `index.json`. */
            url: string;
        };
        AddRepoResponse: {
            repo: components["schemas"]["RepoView"];
            sync: components["schemas"]["SyncReport"];
        };
        ApiKeyInfo: {
            /**
             * Format: int64
             * @description Unix ms.
             */
            created_at: number;
            id: string;
            /** Format: int64 */
            last_used_at?: number | null;
            name: string;
        };
        /** @description What kinds of query a provider supports. */
        Capabilities: {
            imdb_search: boolean;
            paging: boolean;
            text_search: boolean;
        };
        /**
         * @description Content category. Providers map their own category ids onto these.
         * @enum {string}
         */
        Category: "movies" | "tv" | "music" | "books" | "software" | "games" | "anime" | "other";
        CheckDefinitionRequest: {
            yaml: string;
        };
        /** @description The outcome of a conversion. */
        Conversion: {
            /** @description Validation problems, if not valid. */
            errors: string[];
            /** @description Whether the result passes validation as is. */
            valid: boolean;
            /** @description Things that couldn't be converted exactly; review them. */
            warnings: string[];
            /** @description The Hashlark definition, as YAML. */
            yaml: string;
        };
        CreateApiKeyRequest: {
            /** @description What the key is for, e.g. "Phone" or "Sonarr". */
            name: string;
        };
        /** @description Result of checking a definition without saving it. */
        DefinitionCheck: {
            errors: string[];
            id?: string | null;
            name?: string | null;
            ok: boolean;
            /** Format: int32 */
            version?: number | null;
        };
        /** @enum {string} */
        DohResolver: "cloudflare" | "quad9" | "google" | "custom";
        DohSettings: {
            /**
             * Format: uri
             * @description Custom DoH endpoint, used when `resolver` is `custom`.
             * @default null
             */
            custom_url: string | null;
            /** @default true */
            enabled: boolean;
            /**
             * @description Fall back to the system resolver if DoH fails.
             * @default true
             */
            fallback_to_system: boolean;
            /** @default cloudflare */
            resolver: components["schemas"]["DohResolver"];
        };
        DownloadSettings: {
            /**
             * @description Where `.torrent` files are saved. `None` means the OS downloads folder.
             * @default null
             */
            torrent_dir: string | null;
        };
        /** @description What to hand to the OS to start a download. */
        DownloadTarget: {
            /** @enum {string} */
            type: "magnet";
            url: string;
        } | {
            /** @enum {string} */
            type: "torrent_file";
            /** Format: uri */
            url: string;
        };
        /** @description Body of every error response. */
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            /** @description Stable machine-readable code, e.g. `not_found`. */
            code: string;
            /** @description For `invalid_definition`: every problem found. */
            details?: string[] | null;
            message: string;
            provider_error?: components["schemas"]["ErrorKind"] | null;
        };
        /**
         * @description Stable, serializable category of a [`ProviderError`].
         * @enum {string}
         */
        ErrorKind: "timeout" | "blocked" | "challenge_required" | "auth_failed" | "rate_limited" | "parse_failed" | "http" | "network";
        /** @description A saved result. */
        Favorite: {
            result: components["schemas"]["MergedResult"];
            /**
             * Format: int64
             * @description Unix ms when it was saved.
             */
            saved_at: number;
        };
        FetchPageRequest: {
            url: string;
        };
        /** @description A page fetched for the definition editor. */
        FetchedPage: {
            html: string;
            /** Format: int32 */
            status: number;
            /** @description Final URL after redirects. */
            url: string;
        };
        Health: {
            /** Format: int64 */
            schema_version?: number | null;
            status: string;
            version: string;
        };
        /**
         * @description Overall state shown next to a provider.
         * @enum {string}
         */
        HealthState: "unknown" | "ok" | "degraded" | "failing" | "auto_disabled";
        HealthSummary: {
            /** Format: int32 */
            consecutive_failures: number;
            /**
             * Format: int64
             * @description Unix ms until which the provider is skipped, if auto-disabled.
             */
            disabled_until?: number | null;
            /**
             * Format: int64
             * @description Unix ms of the last attempt.
             */
            last_checked_at?: number | null;
            last_error_kind?: components["schemas"]["ErrorKind"] | null;
            /** Format: int64 */
            p50_ms?: number | null;
            /** Format: int64 */
            p95_ms?: number | null;
            state: components["schemas"]["HealthState"];
            /**
             * Format: float
             * @description Share of successful attempts in the recent window.
             */
            success_rate?: number | null;
        };
        /** @description One saved search. */
        HistoryEntry: {
            /** Format: int64 */
            id: number;
            query: components["schemas"]["SearchQuery"];
            /** Format: int64 */
            result_count: number;
            /**
             * Format: int64
             * @description Unix ms.
             */
            ts: number;
        };
        MagnetSettings: {
            /**
             * @description Add the default trackers to magnets that already list their own.
             * @default false
             */
            append_default_trackers: boolean;
            /**
             * Format: uri
             * @description URL of a plain-text tracker list (one per line), refreshed daily.
             * @default null
             */
            trackers_url: string | null;
        };
        /**
         * @description A result after de-duplication across providers. This is what front ends
         *     display.
         */
        MergedResult: {
            /**
             * @description Stable id: derived from the infohash when known, so the same torrent
             *     keeps its id across searches.
             */
            id: string;
            /**
             * Format: int32
             * @description Highest leecher count reported by any source.
             */
            leechers?: number | null;
            /**
             * @description Best combined view of the result. Missing fields are filled in from
             *     other sources as they arrive.
             */
            primary: components["schemas"]["SearchResult"];
            /**
             * Format: float
             * @description Relevance score in `0.0..=1.0`.
             */
            score: number;
            /**
             * Format: int32
             * @description Highest seeder count reported by any source.
             */
            seeders?: number | null;
            /** @description Every provider that returned this torrent, in arrival order. */
            sources: components["schemas"]["ProviderId"][];
        };
        /** @description Per-provider network policy. */
        NetworkPolicy: {
            /**
             * @description Used when `route` is `proxy`.
             * @default null
             */
            proxy: string | null;
            /** @default default */
            route: components["schemas"]["Route"];
        };
        NetworkSettings: {
            /**
             * @default {
             *       "custom_url": null,
             *       "enabled": true,
             *       "fallback_to_system": true,
             *       "resolver": "cloudflare"
             *     }
             */
            doh: components["schemas"]["DohSettings"];
            /**
             * Format: int32
             * @description Requests per second allowed to one host.
             * @default 1
             */
            per_host_rate: number;
            /**
             * Format: uri
             * @description Global proxy, e.g. `socks5h://127.0.0.1:9050` or `http://proxy:8080`.
             * @default null
             */
            proxy: string | null;
            /**
             * @default {
             *       "enabled": false,
             *       "mode": "embedded",
             *       "socks_url": "socks5h://127.0.0.1:9050"
             *     }
             */
            tor: components["schemas"]["TorSettings"];
        };
        /** @description A newly created key. The key itself is shown only once. */
        NewApiKey: components["schemas"]["ApiKeyInfo"] & {
            key: string;
        };
        PreviewDefinitionRequest: {
            categories?: components["schemas"]["Category"][];
            query: string;
            /** @description Setting values (`cfg.*`) to use for this run only. */
            settings?: {
                [key: string]: string;
            };
            yaml: string;
        };
        /** @description Stable identifier of a provider, e.g. `internet-archive`. */
        ProviderId: string;
        /**
         * @description How a provider is implemented (see ADR 0005).
         * @enum {string}
         */
        ProviderKind: "native" | "definition" | "torznab";
        /** @description Result of one provider in a completed search. */
        ProviderOutcome: components["schemas"]["ProviderStatus"] & {
            /** Format: int64 */
            latency_ms: number;
            provider: components["schemas"]["ProviderId"];
        };
        /** @description Changes to a provider. Absent fields are left as they are. */
        ProviderPatch: {
            enabled?: boolean | null;
            name?: string | null;
            network_policy?: components["schemas"]["NetworkPolicy"] | null;
            /** @description Setting values to change; `null` clears one. */
            settings?: {
                [key: string]: string | null;
            } | null;
        };
        /** @description Where a provider comes from. */
        ProviderSource: {
            /** @enum {string} */
            type: "native";
        } | {
            links: string[];
            /** @description Repository it came from; `null` if imported by hand. */
            repo_id?: string | null;
            site_type?: components["schemas"]["SiteType"] | null;
            /** @enum {string} */
            type: "definition";
            /** Format: int64 */
            version: number;
        } | {
            /** @enum {string} */
            type: "torznab";
            url: string;
        };
        ProviderStatus: {
            count: number;
            /** @enum {string} */
            status: "ok";
        } | {
            error_kind: components["schemas"]["ErrorKind"];
            message: string;
            /** @enum {string} */
            status: "failed";
        };
        /** @description A provider as shown to users. */
        ProviderView: {
            /** @description Shipped with Hashlark: can be disabled but not removed. */
            builtin: boolean;
            capabilities?: components["schemas"]["Capabilities"] | null;
            categories: components["schemas"]["Category"][];
            description: string;
            enabled: boolean;
            /** @description Why the provider couldn't be loaded (e.g. an invalid definition). */
            error?: string | null;
            health: components["schemas"]["HealthSummary"];
            id: string;
            kind: components["schemas"]["ProviderKind"];
            name: string;
            network_policy: components["schemas"]["NetworkPolicy"];
            settings: components["schemas"]["SettingView"][];
            source: components["schemas"]["ProviderSource"];
        };
        RefreshTrackersResponse: {
            /** @description Trackers fetched from the list URL. */
            fetched: number;
        };
        /** @description A definition repository as shown to users. */
        RepoView: {
            /** @description Shipped with Hashlark; can't be removed. */
            builtin: boolean;
            /** Format: int64 */
            definitions: number;
            /** @description Short form of the pinned signing key. */
            fingerprint?: string | null;
            id: string;
            /**
             * Format: int64
             * @description Unix ms.
             */
            last_sync_at?: number | null;
            /** Format: int64 */
            last_version?: number | null;
            name?: string | null;
            url: string;
        };
        ResolveRequest: {
            prefer?: components["schemas"]["TargetKind"] | null;
            result_id: string;
        };
        /**
         * @description How a provider's traffic is routed.
         * @enum {string}
         */
        Route: "default" | "direct" | "proxy" | "tor";
        /**
         * @description Progress of a running search, in the order it happens. Front ends render
         *     these as they arrive; the HTTP API forwards them as SSE events.
         */
        SearchEvent: {
            /** @enum {string} */
            event: "provider_started";
            provider: components["schemas"]["ProviderId"];
        } | {
            /** @enum {string} */
            event: "results";
            items: components["schemas"]["MergedResult"][];
            provider: components["schemas"]["ProviderId"];
        } | {
            count: number;
            /** @enum {string} */
            event: "provider_finished";
            /** Format: int64 */
            latency_ms: number;
            provider: components["schemas"]["ProviderId"];
        } | {
            error_kind: components["schemas"]["ErrorKind"];
            /** @enum {string} */
            event: "provider_failed";
            /** Format: int64 */
            latency_ms: number;
            message: string;
            provider: components["schemas"]["ProviderId"];
        } | {
            /** Format: int64 */
            duration_ms: number;
            /** @enum {string} */
            event: "done";
            total: number;
        };
        /** @description A completed search: sorted results plus how each provider did. */
        SearchOutcome: {
            /** Format: int64 */
            duration_ms: number;
            providers: components["schemas"]["ProviderOutcome"][];
            results: components["schemas"]["MergedResult"][];
        };
        /** @description A search request. */
        SearchQuery: {
            /** @description Empty means all categories. */
            categories?: components["schemas"]["Category"][];
            imdb_id?: string | null;
            /**
             * Format: int32
             * @description 1-based page number.
             */
            page?: number;
            /** @description `None` means every enabled provider. */
            providers?: components["schemas"]["ProviderId"][] | null;
            sort?: components["schemas"]["SortOrder"];
            text: string;
        };
        /** @description One result as returned by one provider. */
        SearchResult: {
            category?: components["schemas"]["Category"] | null;
            details_url?: string | null;
            info_hash?: string | null;
            /** Format: int32 */
            leechers?: number | null;
            magnet?: string | null;
            /**
             * @description The download link is only available after [`resolve`] (e.g. it is on
             *     the provider's details page).
             *
             *     [`resolve`]: crate::provider::SearchProvider::resolve
             */
            needs_resolve?: boolean;
            provider_id: components["schemas"]["ProviderId"];
            /** Format: date-time */
            published?: string | null;
            /** Format: int32 */
            seeders?: number | null;
            /** Format: int64 */
            size_bytes?: number | null;
            title: string;
            torrent_url?: string | null;
        };
        SearchSettings: {
            /**
             * Format: int64
             * @description How long identical searches are served from cache, in seconds. 0 disables caching.
             * @default 600
             */
            cache_ttl_secs: number;
            /**
             * @description Maximum providers searched at once.
             * @default 16
             */
            max_concurrency: number;
            /**
             * Format: int64
             * @description How long one provider may take, in seconds.
             * @default 10
             */
            provider_timeout_secs: number;
            /** @default true */
            save_history: boolean;
        };
        /** @description Cookies from a browser check the user completed on the site. */
        Session: {
            cookies: components["schemas"]["SessionCookie"][];
            /**
             * Format: int64
             * @description Unix ms; defaults to 24 hours from now.
             */
            expires_at?: number | null;
            /** @description Page the cookies belong to. */
            url: string;
            /** @description The browser's user agent; challenge cookies only work with it. */
            user_agent?: string | null;
        };
        /** @description One cookie from a browser session. */
        SessionCookie: {
            name: string;
            value: string;
        };
        /** @enum {string} */
        SettingKind: "text" | "password" | "checkbox" | "select";
        /** @description A user-configurable setting of a provider. */
        SettingView: {
            /** @description Whether a value is stored (useful for passwords). */
            is_set: boolean;
            kind: components["schemas"]["SettingKind"];
            label: string;
            name: string;
            options: {
                [key: string]: string;
            };
            required: boolean;
            /** @description Current value; always `null` for passwords. */
            value?: string | null;
        };
        /** @description All user-configurable settings. */
        Settings: {
            /**
             * @default {
             *       "torrent_dir": null
             *     }
             */
            downloads: components["schemas"]["DownloadSettings"];
            /**
             * @default {
             *       "append_default_trackers": false,
             *       "trackers_url": null
             *     }
             */
            magnets: components["schemas"]["MagnetSettings"];
            /**
             * @default {
             *       "doh": {
             *         "custom_url": null,
             *         "enabled": true,
             *         "fallback_to_system": true,
             *         "resolver": "cloudflare"
             *       },
             *       "per_host_rate": 1,
             *       "proxy": null,
             *       "tor": {
             *         "enabled": false,
             *         "mode": "embedded",
             *         "socks_url": "socks5h://127.0.0.1:9050"
             *       }
             *     }
             */
            network: components["schemas"]["NetworkSettings"];
            /**
             * @default {
             *       "cache_ttl_secs": 600,
             *       "max_concurrency": 16,
             *       "provider_timeout_secs": 10,
             *       "save_history": true
             *     }
             */
            search: components["schemas"]["SearchSettings"];
            /**
             * @default {
             *       "first_run_done": false,
             *       "theme": "system"
             *     }
             */
            ui: components["schemas"]["UiSettings"];
            /**
             * @default {
             *       "check_for_updates": true
             *     }
             */
            updates: components["schemas"]["UpdateSettings"];
        };
        /** @enum {string} */
        SiteType: "public" | "semi_private" | "private";
        /**
         * @description How the merged result list is ordered.
         * @enum {string}
         */
        SortOrder: "relevance" | "title" | "seeders" | "peers" | "size" | "date";
        StoredDefinition: {
            id: string;
            /** @description The repository it came from; `None` if imported by hand. */
            repo_id?: string | null;
            sha256: string;
            /**
             * Format: int64
             * @description Unix ms.
             */
            updated_at: number;
            /** Format: int64 */
            version: number;
            yaml: string;
        };
        /** @description What a sync changed. */
        SyncReport: {
            /** @description New providers (added disabled, for the user to review). */
            added: string[];
            /** @description Definitions that were skipped, and why. */
            errors: string[];
            removed: string[];
            unchanged: number;
            updated: string[];
        };
        /**
         * @description Which kind of [`DownloadTarget`] a caller would rather have.
         * @enum {string}
         */
        TargetKind: "magnet" | "torrent_file";
        /** @description Outcome of a manual provider test. */
        TestReport: {
            error_kind?: components["schemas"]["ErrorKind"] | null;
            /** Format: int64 */
            latency_ms: number;
            message?: string | null;
            ok: boolean;
            result_count: number;
        };
        /** @enum {string} */
        Theme: "system" | "light" | "dark";
        /** @enum {string} */
        TorMode: "embedded" | "external";
        TorSettings: {
            /**
             * @description Route every provider through Tor.
             * @default false
             */
            enabled: boolean;
            /**
             * @description Use Hashlark's built-in Tor, or a Tor already running on this
             *     computer (at `socks_url`).
             * @default embedded
             */
            mode: components["schemas"]["TorMode"];
            /**
             * @description SOCKS address of a running Tor (Tor Browser uses port 9150, the Tor
             *     service and Orbot 9050).
             * @default socks5h://127.0.0.1:9050
             */
            socks_url: string | null;
        };
        /** @description State of Tor, for the UI. */
        TorStatus: {
            /** @description Built-in Tor is available in this build. */
            built_in: boolean;
            message: string;
            /**
             * Format: float
             * @description 0.0 to 1.0.
             */
            progress: number;
            /** @description Tor can carry traffic. */
            ready: boolean;
            running: boolean;
        };
        UiSettings: {
            /**
             * @description Set once the user has finished the first-run screen.
             * @default false
             */
            first_run_done: boolean;
            /** @default system */
            theme: components["schemas"]["Theme"];
        };
        UpdateSettings: {
            /**
             * @description Check GitHub Releases for new versions.
             * @default true
             */
            check_for_updates: boolean;
        };
        YamlText: {
            yaml: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_api_keys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyInfo"][];
                };
            };
        };
    };
    create_api_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewApiKey"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    revoke_api_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    check_definition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckDefinitionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefinitionCheck"];
                };
            };
        };
    };
    convert_definition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckDefinitionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversion"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    preview_definition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewDefinitionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The site failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    starter_definition: {
        parameters: {
            query?: {
                /** @description `html` (default), `json` or `rss`. */
                kind?: string;
                /** @description Id for the new definition. */
                id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YamlText"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_definition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredDefinition"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_favorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorite"][];
                };
            };
        };
    };
    add_favorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Result id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorite"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    remove_favorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_history: {
        parameters: {
            query?: {
                /** @description Maximum entries (default 50, max 500). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryEntry"][];
                };
            };
        };
    };
    clear_history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tor_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TorStatus"];
                };
            };
        };
    };
    list_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"][];
                };
            };
        };
    };
    add_provider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProvider"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"];
                };
            };
            /** @description Invalid definition; `details` lists the problems */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Built-in providers can't be removed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderPatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    set_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Session"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderView"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    test_provider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestReport"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_repos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepoView"][];
                };
            };
        };
    };
    add_repo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRepoRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddRepoResponse"];
                };
            };
            /** @description Invalid, unsigned or duplicate repository */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Could not fetch it */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    remove_repo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    sync_repo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncReport"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    resolve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadTarget"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The provider failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_result: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Result id from a search */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergedResult"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    search_stream: {
        parameters: {
            query?: {
                /** @description Text to search for. */
                q?: string;
                /** @description Comma-separated categories, e.g. `movies,tv`. */
                cat?: string;
                /** @description Comma-separated provider ids. Default: all enabled providers. */
                providers?: string;
                /** @description IMDb id, for providers that support it. */
                imdb?: string;
                /** @description 1-based page. Default 1. */
                page?: number;
                /** @description `relevance` (default), `title`, `seeders`, `peers`, `size` or `date`. */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of SearchEvent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SearchEvent"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    search_blocking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchQuery"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOutcome"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    put_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    fetch_page: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchPageRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchedPage"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_trackers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    refresh_trackers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTrackersResponse"];
                };
            };
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
